<?php

declare(strict_types=1);

namespace App\Entity;

use App\Enum\DataProtectionStrategy;
use SentinelPHP\Drift\Enum\DriftSeverity;
use App\Enum\LogLevel;
use App\Enum\TokenMode;
use App\Repository\ApiTokenRepository;
use App\Validation\HostMatcher;
use App\ValueObject\TokenDtoConfiguration;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ApiTokenRepository::class)]
#[ORM\Table(name: 'api_tokens')]
#[ORM\HasLifecycleCallbacks]
class ApiToken
{
    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    private Uuid $id;

    #[ORM\Column(type: Types::STRING, length: 64, unique: true)]
    private string $tokenHash;

    #[ORM\Column(type: Types::STRING, length: 255)]
    #[Assert\NotBlank(message: 'Token name is required.')]
    #[Assert\Length(
        min: 3,
        max: 255,
        minMessage: 'Token name must be at least {{ limit }} characters.',
        maxMessage: 'Token name cannot exceed {{ limit }} characters.'
    )]
    private string $name;

    /** @var list<string> */
    #[ORM\Column(type: Types::JSON)]
    private array $allowedTargets = [];

    #[ORM\Column(type: Types::BOOLEAN)]
    private bool $isActive = true;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    private \DateTimeImmutable $updatedAt;

    #[ORM\Column(type: Types::STRING, length: 20, nullable: true, enumType: LogLevel::class)]
    private ?LogLevel $logLevel = null;

    #[ORM\Column(type: Types::STRING, length: 20, enumType: TokenMode::class)]
    private TokenMode $mode = TokenMode::Passive;

    #[ORM\Column(type: Types::BOOLEAN)]
    private bool $validateRequestBody = false;

    /** @var array<string, string>|null */
    #[ORM\Column(type: Types::JSON, nullable: true)]
    private ?array $severityOverrides = null;

    #[ORM\Column(type: Types::STRING, length: 20, nullable: true, enumType: DriftSeverity::class)]
    private ?DriftSeverity $alertMinSeverity = null;

    #[ORM\Column(type: Types::INTEGER, nullable: true)]
    #[Assert\Positive(message: 'Learning threshold must be a positive number.')]
    private ?int $learningThreshold = null;

    #[ORM\Column(type: Types::BOOLEAN)]
    private bool $autoSwitchToValidating = false;

    #[ORM\Column(type: Types::STRING, length: 20, nullable: true, enumType: DataProtectionStrategy::class)]
    private ?DataProtectionStrategy $dataProtectionStrategy = null;

    /** @var array<string, string>|null */
    #[ORM\Column(type: Types::JSON, nullable: true)]
    #[Assert\Json(message: 'Custom redaction patterns must be valid JSON.')]
    private ?array $customRedactionPatterns = null;

    #[ORM\Column(type: Types::BOOLEAN)]
    private bool $autoGenerateDtos = false;

    /** @var array<string, mixed>|null */
    #[ORM\Column(type: Types::JSON, nullable: true)]
    private ?array $dtoConfiguration = null;

    public function __construct()
    {
        $this->id = Uuid::v7();
        $this->createdAt = new \DateTimeImmutable();
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function getTokenHash(): string
    {
        return $this->tokenHash;
    }

    public function setTokenHash(string $tokenHash): self
    {
        $this->tokenHash = $tokenHash;
        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return list<string>
     */
    public function getAllowedTargets(): array
    {
        return $this->allowedTargets;
    }

    /**
     * @param list<string> $allowedTargets
     */
    public function setAllowedTargets(array $allowedTargets): self
    {
        $this->allowedTargets = $allowedTargets;
        return $this;
    }

    public function isActive(): bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;
        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): \DateTimeImmutable
    {
        return $this->updatedAt;
    }

    #[ORM\PreUpdate]
    public function updateTimestamp(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function isTargetAllowed(string $targetHost): bool
    {
        return HostMatcher::matches($targetHost, $this->allowedTargets);
    }

    public function getLogLevel(): ?LogLevel
    {
        return $this->logLevel;
    }

    public function setLogLevel(?LogLevel $logLevel): self
    {
        $this->logLevel = $logLevel;
        return $this;
    }

    public function getMode(): TokenMode
    {
        return $this->mode;
    }

    public function setMode(TokenMode $mode): self
    {
        $this->mode = $mode;
        return $this;
    }

    public function isValidateRequestBody(): bool
    {
        return $this->validateRequestBody;
    }

    public function setValidateRequestBody(bool $validateRequestBody): self
    {
        $this->validateRequestBody = $validateRequestBody;
        return $this;
    }

    /**
     * @return array<string, string>|null
     */
    public function getSeverityOverrides(): ?array
    {
        return $this->severityOverrides;
    }

    /**
     * @param array<string, string>|null $severityOverrides
     */
    public function setSeverityOverrides(?array $severityOverrides): self
    {
        $this->severityOverrides = $severityOverrides;
        return $this;
    }

    public function getAlertMinSeverity(): ?DriftSeverity
    {
        return $this->alertMinSeverity;
    }

    public function setAlertMinSeverity(?DriftSeverity $alertMinSeverity): self
    {
        $this->alertMinSeverity = $alertMinSeverity;
        return $this;
    }

    public function getLearningThreshold(): ?int
    {
        return $this->learningThreshold;
    }

    public function setLearningThreshold(?int $learningThreshold): self
    {
        $this->learningThreshold = $learningThreshold;
        return $this;
    }

    public function isAutoSwitchToValidating(): bool
    {
        return $this->autoSwitchToValidating;
    }

    public function setAutoSwitchToValidating(bool $autoSwitchToValidating): self
    {
        $this->autoSwitchToValidating = $autoSwitchToValidating;
        return $this;
    }

    public function getDataProtectionStrategy(): ?DataProtectionStrategy
    {
        return $this->dataProtectionStrategy;
    }

    public function setDataProtectionStrategy(?DataProtectionStrategy $dataProtectionStrategy): self
    {
        $this->dataProtectionStrategy = $dataProtectionStrategy;
        return $this;
    }

    /**
     * @return array<string, string>|null
     */
    public function getCustomRedactionPatterns(): ?array
    {
        return $this->customRedactionPatterns;
    }

    /**
     * @param array<string, string>|null $customRedactionPatterns
     */
    public function setCustomRedactionPatterns(?array $customRedactionPatterns): self
    {
        $this->customRedactionPatterns = $customRedactionPatterns;
        return $this;
    }

    public function isAutoGenerateDtos(): bool
    {
        return $this->autoGenerateDtos;
    }

    public function setAutoGenerateDtos(bool $autoGenerateDtos): self
    {
        $this->autoGenerateDtos = $autoGenerateDtos;
        return $this;
    }

    public function getDtoConfiguration(): TokenDtoConfiguration
    {
        if ($this->dtoConfiguration === null) {
            return TokenDtoConfiguration::empty();
        }

        return TokenDtoConfiguration::fromArray($this->dtoConfiguration);
    }

    public function setDtoConfiguration(?TokenDtoConfiguration $dtoConfiguration): self
    {
        $this->dtoConfiguration = $dtoConfiguration?->toArray();
        return $this;
    }

    /**
     * Check if this token has custom DTO configuration.
     */
    public function hasDtoConfiguration(): bool
    {
        return $this->dtoConfiguration !== null && $this->dtoConfiguration !== [];
    }
}
