<?php

declare(strict_types=1);

namespace App\Tests\Integration\EventSubscriber;

use App\Entity\ApiSchema;
use SentinelPHP\Dto\Enum\SchemaType;
use App\Event\SchemaPromotedEvent;
use App\EventSubscriber\DtoAutoGeneratorSubscriber;
use App\Message\GenerateDtoMessage;
use App\Tests\Factories\ApiSchemaFactory;
use App\Tests\Factories\ApiTokenFactory;
use PHPUnit\Framework\Attributes\Test;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Messenger\Transport\InMemory\InMemoryTransport;
use Symfony\Component\Messenger\Transport\TransportInterface;
use Zenstruck\Foundry\Test\Factories;
use Zenstruck\Foundry\Test\ResetDatabase;

final class DtoAutoGeneratorSubscriberTest extends KernelTestCase
{
    use Factories;
    use ResetDatabase;

    private TransportInterface $transport;

    protected function setUp(): void
    {
        self::bootKernel();
        /** @var InMemoryTransport $transport */
        $transport = self::getContainer()->get('messenger.transport.async');
        $this->transport = $transport;
    }

    #[Test]
    public function subscriberDispatchesMessageWhenTokenAutoGenerateEnabled(): void
    {
        $token = ApiTokenFactory::createOne([
            'autoGenerateDtos' => true,
        ]);
        $schema = ApiSchemaFactory::createOne([
            'token' => $token,
            'isMaster' => true,
            'schemaType' => SchemaType::Response,
        ]);

        $subscriber = self::getContainer()->get(DtoAutoGeneratorSubscriber::class);
        $schemaEntity = self::getContainer()->get('doctrine')->getRepository(ApiSchema::class)->find($schema->getId());
        self::assertNotNull($schemaEntity);
        $event = new SchemaPromotedEvent($schemaEntity);

        $subscriber->onSchemaPromoted($event);

        self::assertInstanceOf(InMemoryTransport::class, $this->transport);
        $envelopes = $this->transport->getSent();
        self::assertCount(1, $envelopes);

        $message = $envelopes[0]->getMessage();
        self::assertInstanceOf(GenerateDtoMessage::class, $message);
        self::assertEquals($schema->getId()->toRfc4122(), $message->schemaId);
    }

    #[Test]
    public function subscriberSkipsWhenTokenAutoGenerateDisabled(): void
    {
        $token = ApiTokenFactory::createOne([
            'autoGenerateDtos' => false,
        ]);
        $schema = ApiSchemaFactory::createOne([
            'token' => $token,
            'isMaster' => true,
            'schemaType' => SchemaType::Response,
        ]);

        $subscriber = self::getContainer()->get(DtoAutoGeneratorSubscriber::class);
        $schemaEntity = self::getContainer()->get('doctrine')->getRepository(ApiSchema::class)->find($schema->getId());
        self::assertNotNull($schemaEntity);
        $event = new SchemaPromotedEvent($schemaEntity);

        $subscriber->onSchemaPromoted($event);

        self::assertInstanceOf(InMemoryTransport::class, $this->transport);
        $envelopes = $this->transport->getSent();
        self::assertCount(0, $envelopes);
    }

    #[Test]
    public function subscriberIncludesPreviousMasterInEvent(): void
    {
        $token = ApiTokenFactory::createOne([
            'autoGenerateDtos' => true,
        ]);
        $previousMaster = ApiSchemaFactory::createOne([
            'token' => $token,
            'isMaster' => false,
            'schemaType' => SchemaType::Response,
            'version' => 1,
        ]);
        $newMaster = ApiSchemaFactory::createOne([
            'token' => $token,
            'isMaster' => true,
            'schemaType' => SchemaType::Response,
            'version' => 2,
        ]);

        $subscriber = self::getContainer()->get(DtoAutoGeneratorSubscriber::class);
        $newMasterEntity = self::getContainer()->get('doctrine')->getRepository(ApiSchema::class)->find($newMaster->getId());
        $previousMasterEntity = self::getContainer()->get('doctrine')->getRepository(ApiSchema::class)->find($previousMaster->getId());
        self::assertNotNull($newMasterEntity);
        $event = new SchemaPromotedEvent($newMasterEntity, $previousMasterEntity);

        $subscriber->onSchemaPromoted($event);

        self::assertInstanceOf(InMemoryTransport::class, $this->transport);
        $envelopes = $this->transport->getSent();
        self::assertCount(1, $envelopes);

        $message = $envelopes[0]->getMessage();
        self::assertInstanceOf(GenerateDtoMessage::class, $message);
        self::assertEquals($newMaster->getId()->toRfc4122(), $message->schemaId);
    }

    #[Test]
    public function subscriberListensToCorrectEvent(): void
    {
        $events = DtoAutoGeneratorSubscriber::getSubscribedEvents();

        self::assertArrayHasKey(SchemaPromotedEvent::class, $events);
        self::assertEquals('onSchemaPromoted', $events[SchemaPromotedEvent::class]);
    }
}
