<?php

declare(strict_types=1);

namespace App\Tests\E2E;

use App\Entity\ApiSchema;
use App\Entity\GeneratedDto;
use SentinelPHP\Dto\Enum\SchemaType;
use App\Message\GenerateDtoMessage;
use App\MessageHandler\GenerateDtoMessageHandler;
use App\Repository\GeneratedDtoRepository;
use App\Tests\Factories\ApiSchemaFactory;
use App\Tests\Factories\ApiTokenFactory;
use App\Tests\Factories\UserFactory;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\Messenger\Transport\InMemory\InMemoryTransport;
use Zenstruck\Foundry\Test\Factories;
use Zenstruck\Foundry\Test\ResetDatabase;

/**
 * E2E Test: Learn schema → Promote to master → Generate DTO → Download
 *
 * This test covers the complete flow from schema learning through DTO generation
 * and download, simulating a real user workflow.
 */
final class LearnPromoteGenerateDtoFlowTest extends WebTestCase
{
    use Factories;
    use ResetDatabase;

    public function testCompleteLearnPromoteGenerateDtoFlow(): void
    {
        $client = static::createClient();

        // Step 1: Create admin user and API token with auto-generate enabled
        $adminUser = UserFactory::new()->admin()->create();
        $token = ApiTokenFactory::new()
            ->withKnownToken('e2e-test-token')
            ->create([
                'name' => 'E2E Test API',
                'autoGenerateDtos' => true,
            ]);

        // Step 2: Simulate schema learning by creating a learned schema
        // (In real flow, this would come from proxy intercepting API responses)
        $learnedSchema = ApiSchemaFactory::createOne([
            'token' => $token,
            'targetHost' => 'api.example.com',
            'endpointPath' => '/api/users',
            'httpMethod' => 'GET',
            'schemaType' => SchemaType::Response,
            'isMaster' => false,
            'version' => 1,
            'jsonSchema' => [
                'type' => 'object',
                'properties' => [
                    'id' => ['type' => 'integer'],
                    'name' => ['type' => 'string'],
                    'email' => ['type' => 'string', 'format' => 'email'],
                    'created_at' => ['type' => 'string', 'format' => 'date-time'],
                ],
                'required' => ['id', 'name', 'email'],
            ],
        ]);

        // Step 3: Login as admin
        $client->loginUser($adminUser);

        // Step 4: Navigate to schemas list
        $client->request('GET', '/dashboard/schemas');
        self::assertResponseIsSuccessful();
        self::assertSelectorTextContains('.header-title', 'API Schemas');

        // Step 5: View schema details
        $client->request('GET', '/dashboard/schemas/' . $learnedSchema->getId());
        self::assertResponseIsSuccessful();
        self::assertSelectorTextContains('.header-title', 'Schema Details');

        // Step 6: Promote schema to master and trigger DTO generation
        // We'll manually promote and generate to test the full flow
        $em = self::getContainer()->get('doctrine')->getManager();
        $schemaEntity = $em->getRepository(ApiSchema::class)->find($learnedSchema->getId());
        self::assertNotNull($schemaEntity);
        $schemaEntity->setIsMaster(true);
        $em->flush();

        // Step 7: Trigger DTO generation (simulating what auto-generation would do)
        $handler = self::getContainer()->get(GenerateDtoMessageHandler::class);
        ($handler)(new GenerateDtoMessage($learnedSchema->getId()->toRfc4122()));

        // Step 9: Verify DTO was generated and stored
        $em = self::getContainer()->get('doctrine')->getManager();
        $schemaEntity = $em->getRepository(ApiSchema::class)->find($learnedSchema->getId());
        self::assertNotNull($schemaEntity);

        /** @var GeneratedDtoRepository $dtoRepository */
        $dtoRepository = self::getContainer()->get(GeneratedDtoRepository::class);
        $generatedDto = $dtoRepository->findCurrentBySchema($schemaEntity);

        self::assertNotNull($generatedDto, 'DTO should be generated');
        self::assertStringContainsString('GetApiUsersResponse', $generatedDto->getClassName());
        self::assertTrue($generatedDto->isCurrent());

        // Step 10: Navigate to DTOs list
        $client->request('GET', '/dashboard/dtos');
        self::assertResponseIsSuccessful();

        // Step 11: View generated DTO
        $client->request('GET', '/dashboard/dtos/' . $generatedDto->getId()->toRfc4122());
        self::assertResponseIsSuccessful();

        // Verify PHP code is displayed
        $crawler = $client->getCrawler();
        self::assertStringContainsString('<?php', $crawler->text());
        self::assertStringContainsString('GetApiUsersResponse', $crawler->text());

        // Step 12: Download the DTO
        $client->request('GET', '/dashboard/dtos/' . $generatedDto->getId()->toRfc4122() . '/download');
        self::assertResponseIsSuccessful();
        self::assertStringStartsWith('text/x-php', $client->getResponse()->headers->get('Content-Type') ?? '');

        $contentDisposition = $client->getResponse()->headers->get('Content-Disposition') ?? '';
        self::assertStringContainsString('attachment', $contentDisposition);
        self::assertStringContainsString('.php', $contentDisposition);

        // Step 13: Verify downloaded content is valid PHP
        $phpCode = $client->getResponse()->getContent();
        self::assertIsString($phpCode);
        self::assertStringContainsString('<?php', $phpCode);
        self::assertStringContainsString('declare(strict_types=1);', $phpCode);
        self::assertStringContainsString('final readonly class', $phpCode);
        self::assertStringContainsString('public int $id,', $phpCode);
        self::assertStringContainsString('public string $name,', $phpCode);
        self::assertStringContainsString('public string $email,', $phpCode);
        self::assertStringContainsString('\DateTimeImmutable', $phpCode);
    }

    public function testManualDtoGenerationFromSchemaPage(): void
    {
        $client = static::createClient();

        $adminUser = UserFactory::new()->admin()->create();
        $plainToken = 'manual-test-api-token';
        $token = ApiTokenFactory::new()
            ->withKnownToken($plainToken)
            ->create([
                'name' => 'Manual Test API',
                'autoGenerateDtos' => false, // Auto-generate disabled
            ]);

        $schema = ApiSchemaFactory::createOne([
            'token' => $token,
            'targetHost' => 'api.example.com',
            'endpointPath' => '/api/orders',
            'httpMethod' => 'POST',
            'schemaType' => SchemaType::Response,
            'isMaster' => true,
            'jsonSchema' => [
                'type' => 'object',
                'properties' => [
                    'order_id' => ['type' => 'string', 'format' => 'uuid'],
                    'total' => ['type' => 'number'],
                    'status' => ['type' => 'string', 'enum' => ['pending', 'confirmed', 'shipped']],
                ],
                'required' => ['order_id', 'total', 'status'],
            ],
        ]);

        $client->loginUser($adminUser);

        // Navigate to schema page
        $crawler = $client->request('GET', '/dashboard/schemas/' . $schema->getId());
        self::assertResponseIsSuccessful();

        // Trigger DTO generation via API using known token
        $client->request(
            'POST',
            '/api/dtos/generate',
            [],
            [],
            [
                'HTTP_AUTHORIZATION' => 'Bearer ' . $plainToken,
                'CONTENT_TYPE' => 'application/json',
            ],
            json_encode(['schema_id' => $schema->getId()->toRfc4122()], JSON_THROW_ON_ERROR)
        );

        self::assertResponseStatusCodeSame(202);

        // Process the generation
        /** @var InMemoryTransport $transport */
        $transport = self::getContainer()->get('messenger.transport.async');
        $messages = $transport->getSent();

        $handler = self::getContainer()->get(GenerateDtoMessageHandler::class);
        foreach ($messages as $envelope) {
            $message = $envelope->getMessage();
            if ($message instanceof GenerateDtoMessage) {
                ($handler)($message);
            }
        }

        // Verify DTO was generated
        $em = self::getContainer()->get('doctrine')->getManager();
        $schemaEntity = $em->getRepository(ApiSchema::class)->find($schema->getId());
        self::assertNotNull($schemaEntity);

        /** @var GeneratedDtoRepository $dtoRepository */
        $dtoRepository = self::getContainer()->get(GeneratedDtoRepository::class);
        $generatedDto = $dtoRepository->findCurrentBySchema($schemaEntity);

        self::assertNotNull($generatedDto);
        self::assertStringContainsString('PostApiOrdersResponse', $generatedDto->getClassName());

        // Verify enum was generated
        self::assertStringContainsString('StatusEnum', $generatedDto->getPhpCode());
    }

    public function testDtoVersioningOnSchemaUpdate(): void
    {
        $client = static::createClient();

        $adminUser = UserFactory::new()->admin()->create();
        $token = ApiTokenFactory::createOne(['autoGenerateDtos' => true]);

        // Create initial schema
        $schema = ApiSchemaFactory::createOne([
            'token' => $token,
            'endpointPath' => '/api/products',
            'httpMethod' => 'GET',
            'schemaType' => SchemaType::Response,
            'isMaster' => true,
            'version' => 1,
            'jsonSchema' => [
                'type' => 'object',
                'properties' => [
                    'id' => ['type' => 'integer'],
                    'name' => ['type' => 'string'],
                ],
                'required' => ['id', 'name'],
            ],
        ]);

        $client->loginUser($adminUser);

        // Generate first DTO version
        $handler = self::getContainer()->get(GenerateDtoMessageHandler::class);
        ($handler)(new GenerateDtoMessage($schema->getId()->toRfc4122()));

        $em = self::getContainer()->get('doctrine')->getManager();
        $schemaEntity = $em->getRepository(ApiSchema::class)->find($schema->getId());
        self::assertNotNull($schemaEntity);

        /** @var GeneratedDtoRepository $dtoRepository */
        $dtoRepository = self::getContainer()->get(GeneratedDtoRepository::class);

        $v1Dto = $dtoRepository->findCurrentBySchema($schemaEntity);
        self::assertNotNull($v1Dto);
        self::assertEquals(1, $v1Dto->getVersion());

        // Update schema with new field
        $schemaEntity->setJsonSchema([
            'type' => 'object',
            'properties' => [
                'id' => ['type' => 'integer'],
                'name' => ['type' => 'string'],
                'price' => ['type' => 'number'], // New field
            ],
            'required' => ['id', 'name', 'price'],
        ]);
        $em->flush();

        // Generate second DTO version
        ($handler)(new GenerateDtoMessage($schema->getId()->toRfc4122()));

        // Verify versioning
        $allVersions = $dtoRepository->findAllVersions($schemaEntity);
        self::assertCount(2, $allVersions);

        $currentDto = $dtoRepository->findCurrentBySchema($schemaEntity);
        self::assertNotNull($currentDto);
        self::assertEquals(2, $currentDto->getVersion());
        self::assertTrue($currentDto->isCurrent());
        self::assertStringContainsString('float $price', $currentDto->getPhpCode());

        // Navigate to DTO diff page
        $client->request(
            'GET',
            '/dashboard/dtos/' . $currentDto->getId()->toRfc4122() . '/diff?compare_from=1&compare_to=2'
        );
        self::assertResponseIsSuccessful();
    }
}
