<?php

declare(strict_types=1);

namespace App\Tests\Integration\Service;

use App\Entity\GeneratedDto;
use App\Service\Dto\DtoExporterService;
use App\Service\Dto\DtoExporterServiceInterface;
use App\Tests\Factories\ApiSchemaFactory;
use App\Tests\Factories\GeneratedDtoFactory;
use App\ValueObject\ExportOptions;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Filesystem\Filesystem;
use Zenstruck\Foundry\Test\Factories;
use Zenstruck\Foundry\Test\ResetDatabase;

#[CoversClass(DtoExporterService::class)]
final class DtoExporterServiceTest extends KernelTestCase
{
    use Factories;
    use ResetDatabase;

    private DtoExporterServiceInterface $exporter;
    private Filesystem $filesystem;
    private string $testOutputDir;

    protected function setUp(): void
    {
        self::bootKernel();
        $container = self::getContainer();

        /** @var DtoExporterServiceInterface $exporter */
        $exporter = $container->get(DtoExporterServiceInterface::class);
        $this->exporter = $exporter;

        $this->filesystem = new Filesystem();
        $this->testOutputDir = sys_get_temp_dir() . '/sentinel_dto_test_' . bin2hex(random_bytes(4));
        $this->filesystem->mkdir($this->testOutputDir);
    }

    protected function tearDown(): void
    {
        if ($this->filesystem->exists($this->testOutputDir)) {
            $this->filesystem->remove($this->testOutputDir);
        }

        parent::tearDown();
    }

    #[Test]
    public function itExportsSingleDtoToCorrectPath(): void
    {
        $dto = GeneratedDtoFactory::createOne([
            'className' => 'GetUsersResponse',
            'namespace' => 'App\\Dto\\Generated',
        ]);

        $result = $this->exporter->exportDto($dto, $this->testOutputDir);

        self::assertTrue($result->isSuccess());
        self::assertCount(1, $result->filesWritten);
        self::assertStringEndsWith('GetUsersResponse.php', $result->filesWritten[0]);
        self::assertFileExists($result->filesWritten[0]);
    }

    #[Test]
    public function itCreatesDirectoryStructureFromNamespace(): void
    {
        $dto = GeneratedDtoFactory::createOne([
            'className' => 'UserDto',
            'namespace' => 'App\\Dto\\Generated\\Users',
        ]);

        $result = $this->exporter->exportDto($dto, $this->testOutputDir);

        self::assertTrue($result->isSuccess());
        $expectedPath = $this->testOutputDir . '/Users/UserDto.php';
        self::assertContains($expectedPath, $result->filesWritten);
        self::assertFileExists($expectedPath);
    }

    #[Test]
    public function itAddsFileHeaderWithMetadata(): void
    {
        $dto = GeneratedDtoFactory::createOne([
            'className' => 'TestResponse',
            'namespace' => 'App\\Dto\\Generated',
        ]);

        $result = $this->exporter->exportDto($dto, $this->testOutputDir);

        self::assertTrue($result->isSuccess());
        $content = file_get_contents($result->filesWritten[0]);
        self::assertIsString($content);

        self::assertStringContainsString('AUTO-GENERATED FILE - DO NOT EDIT', $content);
        self::assertStringContainsString('Generated by Sentinel PHP DTO Generator', $content);
        self::assertStringContainsString('Generated at:', $content);
        self::assertStringContainsString('Schema ID:', $content);
        self::assertStringContainsString('Version:', $content);
    }

    #[Test]
    public function itSupportsDryRunMode(): void
    {
        $dto = GeneratedDtoFactory::createOne([
            'className' => 'DryRunTest',
            'namespace' => 'App\\Dto\\Generated',
        ]);

        $options = ExportOptions::dryRun();
        $result = $this->exporter->exportDto($dto, $this->testOutputDir, $options);

        self::assertTrue($result->isSuccess());
        self::assertTrue($result->dryRun);
        self::assertCount(1, $result->filesWritten);
        self::assertFileDoesNotExist($result->filesWritten[0]);
    }

    #[Test]
    public function itCreatesBackupBeforeOverwrite(): void
    {
        $dto = GeneratedDtoFactory::createOne([
            'className' => 'BackupTest',
            'namespace' => 'App\\Dto\\Generated',
        ]);

        $this->exporter->exportDto($dto, $this->testOutputDir);

        $result = $this->exporter->exportDto($dto, $this->testOutputDir, ExportOptions::default());

        self::assertTrue($result->isSuccess());
        self::assertCount(1, $result->backupsCreated);
        self::assertStringEndsWith('.bak', $result->backupsCreated[0]);
        self::assertFileExists($result->backupsCreated[0]);
    }

    #[Test]
    public function itSkipsBackupWhenDisabled(): void
    {
        $dto = GeneratedDtoFactory::createOne([
            'className' => 'NoBackupTest',
            'namespace' => 'App\\Dto\\Generated',
        ]);

        $this->exporter->exportDto($dto, $this->testOutputDir);

        $options = ExportOptions::noBackup();
        $result = $this->exporter->exportDto($dto, $this->testOutputDir, $options);

        self::assertTrue($result->isSuccess());
        self::assertCount(0, $result->backupsCreated);
    }

    #[Test]
    public function itSkipsFileWhenOverwriteDisabled(): void
    {
        $dto = GeneratedDtoFactory::createOne([
            'className' => 'NoOverwriteTest',
            'namespace' => 'App\\Dto\\Generated',
        ]);

        $this->exporter->exportDto($dto, $this->testOutputDir);

        $options = (new ExportOptions())->withOverwrite(false);
        $result = $this->exporter->exportDto($dto, $this->testOutputDir, $options);

        self::assertTrue($result->isSuccess());
        self::assertCount(0, $result->filesWritten);
        self::assertCount(1, $result->filesSkipped);
    }

    #[Test]
    public function itExportsAllCurrentDtos(): void
    {
        $schema1 = ApiSchemaFactory::createOne();
        $schema2 = ApiSchemaFactory::createOne();

        GeneratedDtoFactory::createOne([
            'schema' => $schema1,
            'className' => 'FirstDto',
            'namespace' => 'App\\Dto\\Generated',
            'isCurrent' => true,
        ]);

        GeneratedDtoFactory::createOne([
            'schema' => $schema2,
            'className' => 'SecondDto',
            'namespace' => 'App\\Dto\\Generated',
            'isCurrent' => true,
        ]);

        $result = $this->exporter->exportAll($this->testOutputDir);

        self::assertTrue($result->isSuccess());
        self::assertCount(2, $result->filesWritten);
    }

    #[Test]
    public function itExportsBundledDtosToSingleFile(): void
    {
        $schema1 = ApiSchemaFactory::createOne();
        $schema2 = ApiSchemaFactory::createOne();

        $dto1 = GeneratedDtoFactory::createOne([
            'schema' => $schema1,
            'className' => 'BundledFirst',
            'namespace' => 'App\\Dto\\Generated',
            'phpCode' => "<?php\n\ndeclare(strict_types=1);\n\nnamespace App\\Dto\\Generated;\n\nfinal readonly class BundledFirst\n{\n    public function __construct(\n        public int \$id,\n    ) {\n    }\n}",
        ]);

        $dto2 = GeneratedDtoFactory::createOne([
            'schema' => $schema2,
            'className' => 'BundledSecond',
            'namespace' => 'App\\Dto\\Generated',
            'phpCode' => "<?php\n\ndeclare(strict_types=1);\n\nnamespace App\\Dto\\Generated;\n\nfinal readonly class BundledSecond\n{\n    public function __construct(\n        public int \$id,\n    ) {\n    }\n}",
        ]);

        $result = $this->exporter->exportBundled(
            [$dto1, $dto2],
            'bundled.php',
            $this->testOutputDir
        );

        self::assertTrue($result->isSuccess());
        self::assertCount(1, $result->filesWritten);

        $content = file_get_contents($result->filesWritten[0]);
        self::assertIsString($content);
        self::assertStringContainsString('BundledFirst', $content);
        self::assertStringContainsString('BundledSecond', $content);
        self::assertStringContainsString('Contains: 2 DTO class(es)', $content);
    }

    #[Test]
    public function itCreatesGitignoreFile(): void
    {
        $result = $this->exporter->createGitignore($this->testOutputDir);

        self::assertTrue($result->isSuccess());
        self::assertCount(1, $result->filesWritten);

        $gitignorePath = $this->testOutputDir . '/.gitignore';
        self::assertFileExists($gitignorePath);

        $content = file_get_contents($gitignorePath);
        self::assertIsString($content);
        self::assertStringContainsString('Auto-generated DTOs', $content);
        self::assertStringContainsString('!.gitignore', $content);
    }

    #[Test]
    public function itSkipsGitignoreIfAlreadyExists(): void
    {
        $this->exporter->createGitignore($this->testOutputDir);

        $result = $this->exporter->createGitignore($this->testOutputDir);

        self::assertTrue($result->isSuccess());
        self::assertCount(0, $result->filesWritten);
        self::assertCount(1, $result->filesSkipped);
    }

    #[Test]
    public function itReturnsErrorWhenNoDtosFoundForSchema(): void
    {
        $schema = ApiSchemaFactory::createOne();

        $result = $this->exporter->exportBySchema($schema, $this->testOutputDir);

        self::assertTrue($result->hasErrors());
        self::assertStringContainsString('No DTO found', $result->errors[0]);
    }

    #[Test]
    public function itReturnsErrorWhenNoDtosFoundForExportAll(): void
    {
        $result = $this->exporter->exportAll($this->testOutputDir);

        self::assertTrue($result->hasErrors());
        self::assertStringContainsString('No DTOs found', $result->errors[0]);
    }

    #[Test]
    public function itCalculatesBytesWritten(): void
    {
        $dto = GeneratedDtoFactory::createOne([
            'className' => 'BytesTest',
            'namespace' => 'App\\Dto\\Generated',
        ]);

        $result = $this->exporter->exportDto($dto, $this->testOutputDir);

        self::assertTrue($result->isSuccess());
        self::assertGreaterThan(0, $result->bytesWritten);
    }

    #[Test]
    public function itGeneratesCorrectFilePath(): void
    {
        $dto = GeneratedDtoFactory::createOne([
            'className' => 'PathTest',
            'namespace' => 'App\\Dto\\Generated\\Sub\\Nested',
        ]);

        $filePath = $this->exporter->getFilePath($dto, $this->testOutputDir);

        self::assertStringEndsWith('Sub/Nested/PathTest.php', $filePath);
    }
}
