<?php

declare(strict_types=1);

namespace App\EventSubscriber;

use App\Event\SchemaPromotedEvent;
use App\Message\GenerateDtoMessage;
use Psr\Log\LoggerInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Messenger\MessageBusInterface;

final readonly class DtoAutoGeneratorSubscriber implements EventSubscriberInterface
{
    public function __construct(
        private MessageBusInterface $messageBus,
        private LoggerInterface $logger,
        private bool $globalAutoGenerateEnabled = false,
    ) {
    }

    public static function getSubscribedEvents(): array
    {
        return [
            SchemaPromotedEvent::class => 'onSchemaPromoted',
        ];
    }

    public function onSchemaPromoted(SchemaPromotedEvent $event): void
    {
        $schema = $event->schema;
        $token = $schema->getToken();

        // Check if auto-generation is enabled (per-token setting takes precedence)
        $shouldGenerate = $token->isAutoGenerateDtos() || $this->globalAutoGenerateEnabled;

        if (!$shouldGenerate) {
            $this->logger->debug('DTO auto-generation skipped (disabled)', [
                'schema_id' => $schema->getId()->toRfc4122(),
                'token_id' => $token->getId()->toRfc4122(),
                'token_auto_generate' => $token->isAutoGenerateDtos(),
                'global_auto_generate' => $this->globalAutoGenerateEnabled,
            ]);

            return;
        }

        $this->logger->info('Dispatching DTO generation message', [
            'schema_id' => $schema->getId()->toRfc4122(),
            'endpoint' => sprintf('%s %s', $schema->getHttpMethod(), $schema->getEndpointPath()),
        ]);

        $this->messageBus->dispatch(new GenerateDtoMessage($schema->getId()->toRfc4122()));
    }
}
