<?php

declare(strict_types=1);

namespace App\Event;

use App\Entity\GeneratedDto;

final readonly class DtoGeneratedEvent
{
    public function __construct(
        public GeneratedDto $dto,
        public bool $wasAutoGenerated = true,
    ) {
    }
}
